export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum VenueType {
  BADMINTON = 'BADMINTON',
  BASKETBALL = 'BASKETBALL',
  TENNIS = 'TENNIS',
  TABLE_TENNIS = 'TABLE_TENNIS',
  FOOTBALL = 'FOOTBALL',
  SWIMMING = 'SWIMMING',
  FITNESS = 'FITNESS',
  MULTI = 'MULTI',
}

export enum VenueStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  MAINTENANCE = 'MAINTENANCE',
  DELETED = 'DELETED',
}

export enum SlotStatus {
  AVAILABLE = 'AVAILABLE',
  FULL = 'FULL',
  CLOSED = 'CLOSED',
  ADMIN_ONLY = 'ADMIN_ONLY',
  RESERVED = 'RESERVED',
  OUT_OF_HOURS = 'OUT_OF_HOURS',
}

export enum BookingSource {
  USER = 'USER',
  ADMIN = 'ADMIN',
}

export enum BookingStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CONFIRMED = 'CONFIRMED',
  CHECKED_IN = 'CHECKED_IN',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REFUNDING = 'REFUNDING',
  REFUNDED = 'REFUNDED',
  EXPIRED = 'EXPIRED',
}

export enum PaymentStatus {
  UNPAID = 'UNPAID',
  PAID = 'PAID',
  REFUNDED = 'REFUNDED',
}

export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAID = 'PAID',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  EXPIRED = 'EXPIRED',
}
